#!/bin/sh

# Play the volume changed sound
canberra-gtk-play -i audio-volume-change -d "changeVolume"

# Arbitrary but unique message tag
msgTag="myvolume"

# Change the volume using pulseaudio
if [ "$@" = "0" ]; then
    pactl set-sink-mute @DEFAULT_SINK@ toggle > /dev/null
else
    pactl set-sink-volume @DEFAULT_SINK@ "$@" > /dev/null
fi

# Query amixer for the current volume and whether or not the speaker is muted
volume="$(pactl get-sink-volume @DEFAULT_SINK@ | awk -F '/' '{print $2}' | grep -o '[0-9]\+')"
mute="$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')"
if [ "$volume" = 0 ] || [ "$mute" = "yes" ]; then
    # Show the sound muted notification
    notify-send -t 3000 -a "changeVolume" -u low -i "~/.local/share/icons/sound/mute.png" -h string:x-dunst-stack-tag:$msgTag "Volume muted"
else
    # Show the volume notification
    notify-send -t 3000 -a "changeVolume" -u low -i "~/.local/share/icons/sound/high-volume.png" -h string:x-dunst-stack-tag:$msgTag \
    -h int:value:"$volume" "Volume: ${volume}%"
fi
