#!/bin/sh

file=$(find -L \
	"$HOME/repos" \
	"$HOME/Packt" \
	"$HOME/.config" | fzf --reverse --height=40%)

[ -z "$file" -o ! -e "$file" ] && exit

case "$file" in
	*pdf)
		zathura --fork "$file" && exit
		;;
	*)
		cd "$(dirname "$file")" || return
		if [ -d "$file" ]; then ranger
		else "$EDITOR" "$file"
		fi
		;;
esac
