#!/bin/sh

file=$(find -L \
	"$HOME/dev" \
	"$HOME/repos" \
	"$HOME/.config" | fzf --reverse --height=40% --preview='preview {}')

[ -z "$file" -o ! -e "$file" ] && exit

case "$file" in
	*.org) "$VISUAL" "$file" ;;
	*.jpg|*.png|*.gif) sxiv "$file" ;;
	*.mkv|*.mp3|*.mp4|*.flac|*.webp) vlc "$file" ;;
	*.pdf) zathura "$file" ;;
	*) [ -d "$file" ] && lf "$file" || "$EDITOR" "$file" ;;
esac
