#!/bin/sh

cleanup() {
    exec 3>&-
	rm "$FIFO_UEBERZUG"
}

# if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
# 	lf "$@"
# else
[ ! -d "$HOME/.cache/lf" ] && mkdir --parents "$HOME/.cache/lf"
export FIFO_UEBERZUG="$HOME/.cache/lf/ueberzug-$$"
mkfifo "$FIFO_UEBERZUG"
ueberzug layer -s <"$FIFO_UEBERZUG" -p json &
exec 3>"$FIFO_UEBERZUG"
trap cleanup EXIT

	# lf "$@" 3>&-
# fi

media="$(find -L \
    "/mnt/HDD/ANIME" "/mnt/HDD/MOVIES-SERIES" "/mnt/HDD/MUSIC" \
    "/mnt/WD/ANIME" "/mnt/WD/MOVIES-SERIES" "/mnt/WD/MUSIC" 2> /dev/null \
    | fzf --reverse --height=40% --preview="FIFO_UEBERZUG='$FIFO_UEBERZUG' preview {}")"

[ -z "$media" -o ! -e "$media" ] && exit 1

case "$file" in
	*.mkv|*.mp3|*.mp4|*.flac|*.webp) mpv "$file" ;;
	*.pdf) zathura "$file" ;;
	*) [ -d "$file" ] && lf "$file" || "$EDITOR" "$file" ;;
esac
