#!/bin/sh

internal="eDP-1"
external1="DP-1"
external2="HDMI-1-0"

xrandr --rate 144
xrandr --output HDMI-1-0 --mode 1920x1080 --rate 144 --primary \
    --output DP-1 --mode 1920x1080 --rate 144 --right-of HDMI-1-0 \
    --output eDP-1 --mode 1920x1080 --left-of HDMI-1-0
# if [ "$(xrandr | grep "$external1" | awk '{print $2}' | tail -n 1)" = 'connected' ]; then
# 	xrandr --output $internal --off --rate 144 --output $external1 --primary --mode 1920x1080 --rate 144
# 	# xrandr --output $internal --off
# 	# xrandr --rate 144
# 	# xrandr --output $external1 --primary --mode 1920x1080 --rate 144
# 	[ "$(xrandr | grep "$external2" | awk '{print $2}' | tail -n 1)" = 'connected' ] && xrandr --output $external2 --mode 1920x1080 --rate 144 --left-of $external1
# elif [ "$(xrandr | grep "$external2" | awk '{print $2}' | tail -n 1)" = 'connected' ]; then
# 	xrandr --output $internal --off --rate 144 --output $external2 --primary --mode 1920x1080 --rate 144
# 	# xrandr --output $internal --off
# 	# xrandr --rate 144
# 	# xrandr --output $external2 --primary --mode 1920x1080
# fi
