#!/bin/sh

mountable=$(lsblk -lp | grep "part $" | awk '{print $1, "(" $4 ")"}')
[ -z "$mountable" ] && exit 1
chosen=$(echo "$mountable" | dmenu -i -p "Mount which drive?" | awk '{print $1}')
[ -z "$chosen" ] && exit 1

sudo mount "$chosen" 2> /dev/null && exit 0

dirs=$(find /mnt /media /home/ -type d -maxdepth 3 2> /dev/null)
mountpoint=$(echo "$dirs" | dmenu -i -p "Enter mountpoint for $chosen")

if [ ! -d "$mountpoint" ]; then
	mkdiryn=$(echo -e "Yes\nNo" | dmenu -i -p "$mountpoint does not exist; create it?")
	[ "$mkdiryn" = "Yes" ] && sudo mkdir -p "$mountpoint"
fi

sudo mount "$chosen" "$mountpoint" && notify-send "$chosen mounted at $mountpoint"
