#! /bin/sh

fzzf() {
	fzf --reverse \
		--ansi \
		--min-height=7 --height=7% \
		--cycle -m --marker="*" \
		--bind 'tab:down' --bind 'btab:up' \
		--bind 'shift-down:toggle+down' --bind 'shift-up:toggle+up'
}

_gen() {
	tmpmail -g "$1" >/dev/null || exit 1
	sed -i "s/^$IDF//" "$PMAILS"
	if [ -z "$(grep "^$1$" "$PMAILS")" ]; then
		printf "%s%s\n" "$IDF" "$1" >> "$PMAILS"
	else
		sed -i "s/^$1$/$IDF$1/" "$PMAILS"
	fi
}

get() {
	if [ -z "$1" ]; then
		tmpmail
	else
		tmpmail "$1"
	fi
}

list() {
	cat "$PMAILS"
}

drop() {
	sel="$(sed "/^$IDF/d" "$PMAILS" | fzzf)"
	[ -z "$sel" ] && exit 0
	printf "%s\n%s\n" "Are you sure you want to delete the following email address(es) from the list?" "$(echo "$sel" | sed 's/^/- /')"

	choice="$(printf "Yes\nNo\n" | fzzf)"
	[ -z "$choice" -o "$choice" = "No" ] && printf "%s\n" "Aborting..." && exit 0

	regex="$(echo "$sel" | sed -z 's/\n/|/g ; s/|$// ; s/^/\(/ ; s/$/\)/')"
	sed -r -i "/$regex/d" "$PMAILS"
}

choose() {
	printf "%s %s\n" "Currently monitoring:" "$(grep "$IDF" "$PMAILS" | sed "s/$IDF//")"
	chosen="$(sed "/^$IDF/d" "$PMAILS" | fzzf)"
	_gen "$chosen"
	printf "%s %s\n" "Now monitoring:" "$chosen"
}

new() {
	if [ -n "$1" ]; then
		_gen "$1"
	else
		printf "%s" "No email address was given, type one now: "
		read n
		_gen "$n"
	fi
}

reset() {
	current="$(grep "$IDF" "$PMAILS" | sed "s/$IDF//")"
	sed -i "s/^$IDF//g" "$PMAILS"
	cat "$PMAILS" | while read l; do
		_gen "$l"
	done
	_gen "$current"
}

docs() {
	printf "CLI utility to interact with tmpmail. \nAvailable commands:\n"
# ~~~ GET ~~~ #
	printf "\t${ACCENT}> %s\n" "${GREEN}g${ACCENT}|${GREEN}get${ACCENT}: ${NORMAL}get most recent emails from pmail being monitored"
# ~~~ LIST ~~~ #
	printf "\t${ACCENT}> %s\n" "${GREEN}l${ACCENT}|${GREEN}ls${ACCENT}|${GREEN}list${ACCENT}: ${NORMAL}list out all available pmails"
# ~~~ DROP ~~~ #
	printf "\t${ACCENT}> %s\n" "${GREEN}d${ACCENT}|${GREEN}dr${ACCENT}|${GREEN}drop${ACCENT}: ${NORMAL}drop one or more of the saved pmails"
# ~~~ CHOOSE ~~~ #
	printf "\t${ACCENT}> %s\n" "${GREEN}c${ACCENT}|${GREEN}choose${ACCENT}: ${NORMAL}choose a different pmail to monitor"
# ~~~ NEW ~~~ #
	printf "\t${ACCENT}> %s\n" "${GREEN}n${ACCENT}|${GREEN}a${ACCENT}|${GREEN}add${ACCENT}|${GREEN}new${ACCENT}: ${NORMAL}add new pmail to the list"
# ~~~ RESET ~~~ #
	printf "\t${ACCENT}> %s\n" "${GREEN}r${ACCENT}|${GREEN}reset${ACCENT}: ${NORMAL}reset monitoring list; run whenver a random email is shown instead of the previously chosen monitoring pmail"
# ~~~ EDIT ~~~ #
	printf "\t${ACCENT}> %s\n" "${GREEN}e${ACCENT}|${GREEN}edit${ACCENT}: ${NORMAL}edit current list of pmails using $EDITOR"
}

PMAILS="$HOME/.local/share/pmail/pmail-list"
IDF=">"
ACCENT="$(tput setaf 12)"
GREEN="$(tput setaf 10)"
RED="$(tput setaf 9)"
NORMAL="$(tput sgr0)"

case "$1" in
	g | get) get "$2" "$3";;
	l | ls | list) list ;;
	d | dr | drop) drop ;;
	c | choose) choose ;;
	n | a | add | new) new "$2" ;;
	r | reset) reset ;;
	e | edit) "$EDITOR" "$PMAILS" ;;
	*) docs ;;
esac
