#!/bin/sh

case "$(file --mime-type "$1" -bL)" in
	text/*) bat --color always "$1" ;;
	application/json) highlight -O ansi "$1" ;;
	application/pdf) pdftotext "$1" - ;;
	image/*) mediainfo "$1" ;;
	video/*) mediainfo "$1" ;;
	*) printf "%s\n" "No clause found for given mime-type"
esac
