#!/bin/sh

[ "$(playerctl -l | head -n 1)" != "spotify" -a "$1" != "force" ] && exit

DIR="$HOME/.local/share/spotify-notif"
[ ! -d "$DIR" ] && mkdir -p "$DIR"
cdn="$($SCRIPTS/spotifycli --arturl)"

[ "$cdn" != "$(cat "$DIR/cdn")" ] && echo "$cdn" > "$DIR/cdn" && curl -s "$cdn" --output "$DIR/cover.png"

dunstify -t 5000 -a "SpotifySong" -u low -i "$DIR/cover.png" -h string:x-dunst-stack-tag:"spotify-notif" "$($SCRIPTS/spotifycli --album)" "$($SCRIPTS/spotifycli --status)"
