#!/bin/sh

drives=$(lsblk -lp | grep "t /" | grep -ve "nvme" | awk '{print $1, "(" $4 ")", "on", $7'})
[ -z "$drives" ] && printf "%s\n" "No drives found to unmount, exiting..." && exit
if [ $(echo "$drives" | wc -l) = 1 ]; then
	chosen=$(echo "$drives" | awk '{print $1}')
else
	chosen=$(echo "$drives" | dmenu -i -p "Unmount which drive?" | awk '{print $1}')
fi
[ -z "$chosen" ] && exit
sudo umount "$chosen" && notify-send "$chosen was unmounted"
